apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-imageupdater
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: argocd-imageupdater
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.12.2
    chart: argocd-image-updater
    helm:
      values: |
        config:
          logLevel: "debug"
          registries: 
            - name: GitHub
              api_url: https://ghcr.io
              prefix: ghcr.io
              credentials: pullsecret:argocd/github-pull-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true