apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: metallb
spec:
  project: default
  source:
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.15.2
    chart: metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true