apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: openebs
spec:
  project: default
  source:
    repoURL: https://openebs.github.io/openebs
    targetRevision: 4.2.0
    chart: openebs
    helm:
      openebs-crds:
        csi:
          volumeSnapshots:
            enabled: true
            keep: true
      # Refer to https://github.com/openebs/dynamic-localpv-provisioner/blob/HEAD/deploy/helm/charts/values.yaml for complete set of values.
      localpv-provisioner:
        rbac:
          create: true
      # Refer to https://github.com/openebs/zfs-localpv/blob/HEAD/deploy/helm/charts/values.yaml for complete set of values.
      zfs-localpv:
        enabled: false
        crds:
          zfsLocalPv:
            enabled: true
          csi:
            volumeSnapshots:
              enabled: false
      # Refer to https://github.com/openebs/lvm-localpv/blob/HEAD/deploy/helm/charts/values.yaml for complete set of values.
      lvm-localpv:
        enabled: false
        crds:
          lvmLocalPv:
            enabled: true
          csi:
            volumeSnapshots:
              enabled: false
      # Refer to https://github.com/openebs/mayastor-extensions/blob/v2.7.0/chart/values.yaml for complete set of values.
      mayastor:
        enabled: false
        csi:
          node:
            initContainers:
              enabled: true
        etcd:
          # -- Kubernetes Cluster Domain
          clusterDomain: cluster.local
        localpv-provisioner:
          enabled: false
        crds:
          enabled: false
      # -- Configuration options for pre-upgrade helm hook job.
      preUpgradeHook:
        image:
          # -- The container image registry URL for the hook job
          registry: docker.io
          # -- The container repository for the hook job
          repo: bitnami/kubectl
          # -- The container image tag for the hook job
          tag: "1.25.15"
          # -- The imagePullPolicy for the container
          pullPolicy: IfNotPresent
      engines:
        local:
          lvm:
            enabled: false
          zfs:
            enabled: false
        replicated:
          mayastor:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: openebs
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true