apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-of-apps
  namespace: argocd
  labels:
    name: apps-of-apps
spec:
  project: apps-of-apps
  source:
    directory:
      recurse: true
    repoURL: https://github.com/chrodrigues/argocd-app-of-apps.git
    path: applications
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true