apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps-of-apps
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/chrodrigues/argocd-app-of-apps.git
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'