apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  labels:
    app.kubernetes.io/part-of: argocd
data:
  policy.csv: |
    p, role:admin, *, *, */*, allow
    g, admin, role:admin
  policy.default: role:readonly
